version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    expose:
      - '3000'
    working_dir: '/usr/src/app'
    environment:
      DB_HOST: 'db'
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:9.5
