defaults: &defaults
  tools:
    default: &default
      icon: selector.png

    rooms:
      <<: *default
      root: apps
      uid: b21211c29d2720a4c847fc3a9097720a196f7fafddbaa0f68d5c1cb54fdbb046
      secret: 3590e00d7ebd398b75c4ea5a65097a19a687d72715af811bc8b3e78aa1664789

    greenlight:
      <<: *default
      root: gl

development:
  <<: *defaults
  product_instance_guid: aada9378-4474-4676-ad7c-db583b43c8d7

test:
  <<: *defaults
  product_instance_guid: a27dfd1f-c372-4a05-a382-7fa782a53570

production:
  <<: *defaults
  product_instance_guid: 048a0d6c-2852-4117-9e32-b7a6c4baf69f
