default: &default
  name: LTI Tool Provider
  icon: selector.png

rooms:
  <<: *default
  root: apps
  secret: abcde-12345
  name: BigBlueButton
  icon: bigbluebutton.svg

greenlight:
  <<: *default
  secret: abcde-12345
  name: Greenlight
  icon: bigbluebutton.svg
